### ISSUE TITLE
Not working for 0.10.28.20959

### ISSUE THREAD

**Issue by luojiesi** [GoToNightmare/DspEnemyThreat#1]
This will make the enemy disappear in some cases. Pressing F7 also does nothing.

**Comment by GoToNightmare** [comment]
https://github.com/GoToNightmare/DspEnemyThreat/assets/34166246/a001cd30-651f-447f-9d18-0a35e1c0e29c

@luojiesi Seems okay. Need more info.

**Comment by luojiesi** [comment]
Okay, I tested it with creating new games multiple times. Some times it worked and some times it didn't. I don't know whether it has something to do with other mods I am using. Updated the list of mods here too.

[Default_1703020939839.zip](https://github.com/GoToNightmare/DspEnemyThreat/files/13720825/Default_1703020939839.zip)

**Comment by GoToNightmare** [comment]
Yeah it could be mod compatibility issue.
Can't check the list, bcs im not using mod manager :(

Try to disable-enable mods one by one
Also if you send me ur save (If ure ok with it lol), i could check it, with my mods setup.
