### ISSUE TITLE
F7 Not Working?

### ISSUE THREAD

**Issue by Shane2894** [GoToNightmare/DspEnemyThreat#2]
F7 should start/stop waves according to description, but instead pauses them from increasing threat % is that what is intended by the mod or is it currently broken?

**Comment by GoToNightmare** [comment]
> F7 should start/stop waves according to description, but instead pauses them from increasing threat % is that what is intended by the mod or is it currently broken?

Yeah thats how it works, threat %
If threat is locked (f7) they shouldn't attack tho
